//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorSOAP.WebServiceSOAPProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="WebServiceSOAPProducto.WebServiceProductoSoap")]
    public interface WebServiceProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/obtenerPrecioConIVAdeProducto", ReplyAction="*")]
        int obtenerPrecioConIVAdeProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/obtenerPrecioConIVAdeProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<int> obtenerPrecioConIVAdeProductoAsync(int idProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProductoSoapChannel : ConsumidorSOAP.WebServiceSOAPProducto.WebServiceProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProductoSoapClient : System.ServiceModel.ClientBase<ConsumidorSOAP.WebServiceSOAPProducto.WebServiceProductoSoap>, ConsumidorSOAP.WebServiceSOAPProducto.WebServiceProductoSoap {
        
        public WebServiceProductoSoapClient() {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int obtenerPrecioConIVAdeProducto(int idProducto) {
            return base.Channel.obtenerPrecioConIVAdeProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task<int> obtenerPrecioConIVAdeProductoAsync(int idProducto) {
            return base.Channel.obtenerPrecioConIVAdeProductoAsync(idProducto);
        }
    }
}
